### ISSUE TITLE
Swift Compiler Error (Xcode): Definition conflicts with previous value

### ISSUE THREAD

**Issue by TheManuz** [ably/ably-flutter#347] opened 2022-03-16 09:32 UTC
I'm receiving the following errors while trying to build with Flutter 2.10.3, XCode 12.3:

```
Could not build the precompiled application for the device.
Uncategorized (Xcode): Command CompileSwift failed with a nonzero exit code

Swift Compiler Error (Xcode): Definition conflicts with previous value
[/Users/TheManuz/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.12/ios/Classes/handlers/PushHandlers.swift:203:18]()
2

Swift Compiler Error (Xcode): Definition conflicts with previous value
[/Users/TheManuz/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.12/ios/Classes/handlers/PushHandlers.swift:207:18]()
2

Swift Compiler Error (Xcode): Unable to infer closure type in the current context
[/Users/TheManuz/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.12/ios/Classes/handlers/PushHandlers.swift:27:152]()
2

Swift Compiler Error (Xcode): Value of optional type 'NSNumber?' must be unwrapped to a value of type 'NSNumber'
[/Users/TheManuz/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.12/ios/Classes/handlers/PushHandlers.swift:212:52]()
2

Swift Compiler Error (Xcode): Value of optional type 'NSNumber?' must be unwrapped to a value of type 'NSNumber'
[/Users/TheManuz/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.12/ios/Classes/handlers/PushHandlers.swift:215:54]()
3
```

Is there something I can to to try to fix it?

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1680) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment] 2022-03-22 11:34
Hi @TheManuz 👋 - we're keen to ensure this is resolved for you. 😁

Did @ikurek's [suggestion](https://github.com/ably/ably-flutter/issues/347#issuecomment-1069201856) help you resolve the issue?
Is there anything else we can do to help unblock you?

**Comment by TheManuz** [comment] 2022-03-22 13:49
Hello @QuintinWillison,

I tried the steps suggested by @ikurek , but they didn't work.

It's probably the XCode version, but I cannot install XCode 13 because it needs Mac OS 12+, and I cannot upgrade my machine because Apple ended the support on it.

A new Mac is on the way, I'll check if the problem is XCode version as suspected.

I suggest to add the minimum requirement in the package description.

**Comment by ikurek** [comment] 2022-03-22 15:31
@TheManuz Please let us know if updating the XCode version solves the issue - if not, we will investigate further

**Comment by heshanka** [comment] 2022-04-18 10:56
I am getting this error with Flutter version 2.8.1 and Xcode 13.2.

**Comment by ikurek** [comment] 2022-04-21 08:39
@heshanka @TheManuz I'm not entirely sure what causes the issue, since I can't reproduce it on my devices. I've issued a potential fix here: https://github.com/ably/ably-flutter/pull/373, but I'd like to get some more information from your side. Can you please provide a list of development tools versions (MacOS, XCode, Swift, etc) and some information about build configuration of your projects?

**Comment by TheManuz** [comment] 2022-04-21 09:52
Sure, here is my configuration:

MacOS Catalina 10.15.7
Xcode 12.3 (12C33)
Swift: version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28), Target: x86_64-apple-darwin19.6.0

> some information about build configuration of your projects

minimum iOS version: 10
target iOS version: 12

@ikurek, feel free to ask any other information might be useful.

Sidenote: I'd like to report if everything is ok on Xcode 13, but sadly the shipping of the new Mac was delayed. I don't know when I'll be able to test this.

Meanwhile I'll try the potential fix.

**Comment by TheManuz** [comment] 2022-04-21 10:16
@ikurek, I copied PushHandlers.swift from [your commit](https://github.com/ably/ably-flutter/pull/373/commits/15bc529135d5a7c1a255f17729840aa0bc6e9412#diff-1280181c9edc1c98e06e673ddcb62e21b97f306071c12a3e552102c84cb4b943), and I didn't work, BUT I received a different error than before, so that's not a bad news.

> Command CompileSwift failed with a nonzero exit code
[/Users/TheManuz/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.13/ios/Classes/handlers/PushHandlers.swift:29:71](): error: failed to produce diagnostic for expression; please file a bug report
            UNUserNotificationCenter.current().getNotificationSettings { [result] settings in
                                                                          ^
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    Result bundle written to path:
    	[/var/folders/h4/w21m7nm91qs6fq7w_tzyzrpr0000gn/T/flutter_tools.P7fvGO/flutter_ios_build_temp_dir1ysP8k/temporary_xcresult_bundle]()
Uncategorized (Xcode): Command CompileSwift failed with a nonzero exit code

> Swift Compiler Error (Xcode): Failed to produce diagnostic for expression; please file a bug report
[/Users/TheManuz/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.13/ios/Classes/handlers/PushHandlers.swift:28:70]()

**Comment by ikurek** [comment] 2022-04-21 11:31
@TheManuz Can you maybe add `import UserNotifications` at the beginning of `PushHandlers.swift` file? It's not directly imported into the file, maybe that's the case?

**Comment by ikurek** [comment] 2022-04-21 15:54
@TheManuz @lawrence-forooghian I've investigated the issue further, and managed to reproduce it with a few virtual environments. Here are some more complete error logs, before changes my PR introduced in [the latest commit](https://github.com/ably/ably-flutter/pull/373/commits/15bc529135d5a7c1a255f17729840aa0bc6e9412#diff-1280181c9edc1c98e06e673ddcb62e21b97f306071c12a3e552102c84cb4b943):

```log
    /Users/vagrant/ably-flutter/ios/Classes/handlers/PushHandlers.swift:188:19: error: definition conflicts with previous value
            guard let handle = handle else {
                      ^
    /Users/vagrant/ably-flutter/ios/Classes/handlers/PushHandlers.swift:182:13: note: previous definition of 'handle' is here
            let handle: NSNumber? = ablyMessage.handle
                ^
    /Users/vagrant/ably-flutter/ios/Classes/handlers/PushHandlers.swift:192:19: error: definition conflicts with previous value
            guard let channelName = channelName else {
                      ^
    /Users/vagrant/ably-flutter/ios/Classes/handlers/PushHandlers.swift:183:13: note: previous definition of 'channelName' is here
            var channelName: String? = nil
                ^
    /Users/vagrant/ably-flutter/ios/Classes/handlers/PushHandlers.swift:28:153: error: unable to infer closure type in the current context
        public static let getNotificationSettings: (_ ably: AblyFlutter, _ call: FlutterMethodCall, _ result: @escaping (_ result: Any?) -> Void) -> Void = { ably, call, result in
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~
    /Users/vagrant/ably-flutter/ios/Classes/handlers/PushHandlers.swift:198:53: error: value of optional type 'NSNumber?' must be unwrapped to a value of type 'NSNumber'
            let realtime = instanceStore.realtime(from: handle)
                                                        ^
    /Users/vagrant/ably-flutter/ios/Classes/handlers/PushHandlers.swift:198:53: note: coalesce using '??' to provide a default when the optional value contains 'nil'
            let realtime = instanceStore.realtime(from: handle)
                                                        ^
                                                               ?? <#default value#>
    /Users/vagrant/ably-flutter/ios/Classes/handlers/PushHandlers.swift:198:53: note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
            let realtime = instanceStore.realtime(from: handle)
                                                        ^
                                                              !
    /Users/vagrant/ably-flutter/ios/Classes/handlers/PushHandlers.swift:201:55: error: value of optional type 'NSNumber?' must be unwrapped to a value of type 'NSNumber'
            } else if let rest = instanceStore.rest(from: handle) {
                                                          ^
    /Users/vagrant/ably-flutter/ios/Classes/handlers/PushHandlers.swift:201:55: note: coalesce using '??' to provide a default when the optional value contains 'nil'
            } else if let rest = instanceStore.rest(from: handle) {
                                                          ^
                                                                 ?? <#default value#>
    /Users/vagrant/ably-flutter/ios/Classes/handlers/PushHandlers.swift:201:55: note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
            } else if let rest = instanceStore.rest(from: handle) {
```

and after the changes it introduced:

```log
    /Users/vagrant/ably-flutter/ios/Classes/handlers/PushHandlers.swift:29:71: error: failed to produce diagnostic for expression; please file a bug report
            UNUserNotificationCenter.current().getNotificationSettings { [result] settings in
                                                                          ^
```

As far as I can tell, specific combination of XCode/MacOS/Swift versions has some sort of bug or undefined behavior, that causes compilation to fail due to those two reasons:

* `guard let handle = handle else { ... }` structure, which was implemented in Swift a while ago, but it doesn't seem to be recognized correctly by the compiler
* the catch of [result] in `getNotificationSettings` method

 I am not able to figure out why the compilation fails, but I can proposed a solution that worked on all test environments that I was able to reproduce this issue on and updated https://github.com/ably/ably-flutter/pull/373.

**Comment by TheManuz** [comment] 2022-04-21 16:26
@ikurek you did it! 🥳 It works! 

Thank you very much!

**Comment by ikurek** [comment] 2022-04-21 16:32
@TheManuz Glad to hear that, and many thanks to @fredyshox for the virtual environments and debugging help 🙂

**Comment by ikurek** [comment] 2022-04-27 09:58
Closing this, since https://github.com/ably/ably-flutter/pull/373 is already merged 🙂

**Closed by ikurek** 2022-04-27 09:58 UTC
Labels: bug
