### ISSUE TITLE
Failing Android build: `The plugin ably_flutter could not be built` URGENT

### ISSUE THREAD

**Issue by heshanka** [ably/ably-flutter#129] opened 2021-06-10 14:38 UTC
My android build keeps failing due to ably with a bunch of  **error: cannot find symbol** which point to @NonNull symbols.

Please have a look.

I am using:
 Flutter V1.22.6. 
 ably_flutter: ^1.2.0-preview.2
 minSdkVersion 24 
 targetSdkVersion 29 
 gradle-6.5-all.zip

---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BUILD FAILED in 5m 10s
Running Gradle task 'assembleBetaRelease'...                      311.2s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin ably_flutter...
Running Gradle task 'assembleAarRelease'...                     inatedResult<T>> paginatedResponseHandler(@NonNull MethodChannel.Result result, Integer handle) {
                                                                            ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:232: error: cannot find symbol
    private void getRestHistory(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                 ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:232: error: cannot find symbol
    private void getRestHistory(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                           ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:248: error: cannot find symbol
    private void getRestPresence(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                  ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:248: error: cannot find symbol
    private void getRestPresence(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                            ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:264: error: cannot find symbol
    private void getRestPresenceHistory(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                         ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:264: error: cannot find symbol
    private void getRestPresenceHistory(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                                   ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:280: error: cannot find symbol
    private void getRealtimePresence(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                      ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:280: error: cannot find symbol
    private void getRealtimePresence(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                                ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:304: error: cannot find symbol
    private void getRealtimePresenceHistory(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                             ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:304: error: cannot find symbol
    private void getRealtimePresenceHistory(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                                       ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:320: error: cannot find symbol
    private void enterRealtimePresence(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                        ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:320: error: cannot find symbol
    private void enterRealtimePresence(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                                  ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:340: error: cannot find symbol
    private void updateRealtimePresence(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                         ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:340: error: cannot find symbol
    private void updateRealtimePresence(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                                   ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:364: error: cannot find symbol
    private void leaveRealtimePresence(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                        ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:364: error: cannot find symbol
    private void leaveRealtimePresence(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                                  ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:388: error: cannot find symbol
    private void createRealtimeWithOptions(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                            ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:388: error: cannot find symbol
    private void createRealtimeWithOptions(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                                      ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:429: error: can   21.0s
WARNING: [Processor] Library '/Users/builder/.gradle/caches/modules-2/files-2.1/io.flutter/flutter_embedding_release/1.0.0-2f0af3715217a0c2ada72c717d4ed9178d68f6ed/78977f0e2f05765acc325f907e1f9a0d27b5024e/flutter_embedding_release-1.0.0-2f0af3715217a0c2ada72c717d4ed9178d68f6ed.jar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/annotation/NonNull'
 Example of support library reference: 'android/support/annotation/NonNull'

/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/StreamsChannel.java:26: error: cannot find symbol
import androidx.annotation.UiThread;
                          ^
  symbol:   class UiThread
  location: package androidx.annotation
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyFlutterMessage.java:3: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:7: error: cannot find symbol
import androidx.annotation.Nullable;
                          ^
  symbol:   class Nullable
  location: package androidx.annotation
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/StreamsChannel.java:70: error: cannot find symbol
    @UiThread
     ^
  symbol:   class UiThread
  location: class StreamsChannel
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/StreamsChannel.java:179: error: cannot find symbol
            @UiThread
             ^
  symbol:   class UiThread
  location: class StreamsChannel.IncomingStreamRequestHandler.EventSinkImplementation
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/StreamsChannel.java:188: error: cannot find symbol
            @UiThread
             ^
  symbol:   class UiThread
  location: class StreamsChannel.IncomingStreamRequestHandler.EventSinkImplementation
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/StreamsChannel.java:199: error: cannot find symbol
            @UiThread
             ^
  symbol:   class UiThread
  location: class StreamsChannel.IncomingStreamRequestHandler.EventSinkImplementation
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyFlutterMessage.java:17: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class AblyFlutterMessage<T>
  where T is a type-variable:
    T extends Object declared in class AblyFlutterMessage
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:121: error: cannot find symbol
    private void handleAblyException(@NonNull MethodChannel.Result result, @NonNull AblyException e) {
                                      ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:121: error: cannot find symbol
    private void handleAblyException(@NonNull MethodChannel.Result result, @NonNull AblyException e) {
                                                                            ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:126: error: cannot find symbol
    public void onMethodCall(@NonNull MethodCall call, @NonNull MethodChannel.Result rawResult) {
                              ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:126: error: cannot find symbol
    public void onMethodCall(@NonNull MethodCall call, @NonNull MethodChannel.Result rawResult) {
                                                        ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:139: error: cannot find symbol
    private CompletionListener handleCompletionWithListener(@NonNull MethodChannel.Result result) {
                                                             ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:153: error: cannot find symbol
    private void register(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                           ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:153: error: cannot find symbol
    private void register(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                     ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:160: error: cannot find symbol
    private void createRestWithOptions(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                        ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:160: error: cannot find symbol
    private void createRestWithOptions(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                                  ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:200: error: cannot find symbol
    private void publishRestMessage(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                     ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:200: error: cannot find symbol
    private void publishRestMessage(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                               ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:217: error: cannot find symbol
    private <T> Callbacknot find symbol
    private void connectRealtime(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                  ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:429: error: cannot find symbol
    private void connectRealtime(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                            ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:441: error: cannot find symbol
            @NonNull MethodCall call, @NonNull MethodChannel.Result result
             ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:441: error: cannot find symbol
            @NonNull MethodCall call, @NonNull MethodChannel.Result result
                                       ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:460: error: cannot find symbol
            @NonNull MethodCall call, @NonNull MethodChannel.Result result
             ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:460: error: cannot find symbol
            @NonNull MethodCall call, @NonNull MethodChannel.Result result
                                       ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:479: error: cannot find symbol
            @NonNull MethodCall call, @NonNull MethodChannel.Result result
             ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:479: error: cannot find symbol
            @NonNull MethodCall call, @NonNull MethodChannel.Result result
                                       ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:499: error: cannot find symbol
            @NonNull MethodCall call, @NonNull MethodChannel.Result result
             ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:499: error: cannot find symbol
            @NonNull MethodCall call, @NonNull MethodChannel.Result result
                                       ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:525: error: cannot find symbol
    private void getRealtimeHistory(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                     ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:525: error: cannot find symbol
    private void getRealtimeHistory(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                               ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:541: error: cannot find symbol
    private void closeRealtime(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:541: error: cannot find symbol
    private void closeRealtime(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                          ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:549: error: cannot find symbol
    private void getNextPage(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                              ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:549: error: cannot find symbol
    private void getNextPage(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                        ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:558: error: cannot find symbol
    private void getFirstPage(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                               ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:558: error: cannot find symbol
    private void getFirstPage(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                         ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:571: error: cannot find symbol
    private void getPlatformVersion(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                     ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:571: error: cannot find symbol
    private void getPlatformVersion(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                               ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:575: error: cannot find symbol
    private void getVersion(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                             ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:575: error: cannot find symbol
    private void getVersion(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                       ^
  symbol:   class NonNull
  location: class AblyMethodCallHandler
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyFlutterPlugin.java:18: error: cannot find symbol
    public void onAttachedToEngine(@NonNull FlutterPluginBinding flutterPluginBinding) {
                                    ^
  symbol:   class NonNull
  location: class AblyFlutterPlugin
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyFlutterPlugin.java:52: error: cannot find symbol
    public void onDetachedFromEngine(@NonNull FlutterPluginBinding binding) {
                                      ^
  symbol:   class NonNull
  location: class AblyFlutterPlugin
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:173: error: cannot find symbol
                                public void success(@Nullable Object result) {
                                                     ^
  symbol: class Nullable
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:178: error: cannot find symbol
                                public void error(String errorCode, @Nullable String errorMessage, @Nullable Object errorDetails) {
                                                                     ^
  symbol: class Nullable
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:178: error: cannot find symbol
                                public void error(String errorCode, @Nullable String errorMessage, @Nullable Object errorDetails) {
                                                                                                    ^
  symbol: class Nullable
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:401: error: cannot find symbol
                                public void success(@Nullable Object result) {
                                                     ^
  symbol: class Nullable
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:408: error: cannot find symbol
                                public void error(String errorCode, @Nullable String errorMessage, @Nullable Object errorDetails) {
                                                                     ^
  symbol: class Nullable
/Users/builder/programs/flutter_1_22_6/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/src/main/java/io/ably/flutter/plugin/AblyMethodCallHandler.java:408: error: cannot find symbol
                                public void error(String errorCode, @Nullable String errorMessage, @Nullable Object errorDetails) {
                                                                                                    ^
  symbol: class Nullable
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
68 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s

The plugin ably_flutter could not be built due to the issue above.

Build failed :|
Failed to build for Android

**Comment by QuintinWillison** [comment] 2021-06-25 08:43
Hello @heshanka - do you get the same issue with [the 1.2.0 release](https://github.com/ably/ably-flutter/releases/tag/v1.2.0) (we pushed that to pub.dev a week ago)? Thanks.

**Comment by heshanka** [comment] 2021-06-25 11:48
I will try and get back to you

**Comment by heshanka** [comment] 2021-06-25 13:31
@QuintinWillison Yes the issue is the same with 1.2.0 as well :/

**Comment by ben-xD** [comment] 2021-06-25 18:45
Hi @heshanka,

- What Android gradle plugin are you using? It might be useful to share your `build.gradle`
- Have you also tried a newer version of Gradle? Instead of `gradle-6.5-all.zip`, try 6.7.1?

**Comment by heshanka** [comment] 2021-06-26 11:05
Hi @ben-xD,

1- I'm using 4.1.1 android gradle plugin version.
2- Yes I tried with 6.7.1 after your comment [with 4.2.0 AGP]- same result :(
3- This is the command I need to be able to execute: 
```flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi --release --obfuscate --split-debug-info=build/app/outputs/symbols --flavor beta -t lib/main_beta.dart```

**Comment by heshanka** [comment] 2021-06-26 11:46
android/build.gradle

```buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
         maven {
             url 'https://maven.fabric.io/public'
            }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.0'
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'io.fabric.tools:gradle:1.28.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://dl.bintray.com/shake/shake' }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by heshanka** [comment] 2021-07-05 14:42
@ben-xD Any updates?

**Comment by ben-xD** [comment] 2021-07-08 07:09
It's quite difficult to debug this, can you provide a reproducible example on github? Thanks 🙂

**Comment by ben-xD** [comment] 2021-09-05 08:05
Closing it since it has been 2 months without a reply.

**Closed** 2021-09-05 08:05 UTC

**Comment by heshanka** [comment] 2021-09-06 08:16
The error was resolved with Flutter 2.0

**Comment by ben-xD** [comment] 2021-09-06 19:15
Excellent! Thanks for letting me know @heshanka

**Comment by heshanka** [comment] 2021-09-07 08:13
Was there a reason for that? @ben-xD  I didnt see it in the requirements to use ably 1.2.0 that we need Flutter >=V2.0
