### ISSUE TITLE
Consider Simplifying AblyMessage

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-flutter#329] opened 2022-02-10 16:02 UTC
I also think this is wrong and should be fixed. BenB emphasised it too before he left. Some data, for some reason gets through the internal message. while other gets through external one, so if we remove the internal one we would probably have to do a bit refactoring from both Flutter and all other platform sides. This might be worth creating an issue maybe? 

_Originally posted by @ikbalkaya in https://github.com/ably/ably-flutter/pull/310#r803833327_

**Comment by ikurek** [comment] 2022-02-10 16:15
@ikbalkaya I think this is a duplicate of https://github.com/ably/ably-flutter/issues/179

**Comment by ikbalkaya** [comment] 2022-02-10 16:18
Oops

**Closed** 2022-02-10 16:19 UTC
