### ISSUE TITLE
When setState within the realtime.connection.on().listen() method

### ISSUE THREAD

**Issue by walkerJung** [ably/ably-flutter#511] opened 2024-03-04 10:58 UTC
```
ablyRealtime.connection.on().listen((event) {
      if (event.current == ably.ConnectionState.connected) {
        if (mounted) {
          setState(() {
            isAblyConnected = true;
          });
        }
      } else {
        if (mounted) {
          setState(() {
            isAblyConnected = false;
          });
        }
      }
    });
```

This is my source code, but initState is adding listeners. Usually the app is in the background. When I come back to foreground, the connection state changes, but if the current state is not connected, I'm trying to show the loading UI, but sometimes I only see a black screen on my Android device. Of course, the iPhone works fine. If anyone is using the loading UI when the connection state is not connected, please advise

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4664) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment] 2024-03-04 11:19
Did you also test this on emulator app? Can you bundle the sample code and upload it as a example app so we can test it from our side?

**Comment by walkerJung** [comment] 2024-03-04 11:22
It is an environment where the connection state is maintained in the simulator and cannot be tested. It only occurs when it is tested with a real device

**Comment by sacOO7** [comment] 2024-03-04 11:30
It seems `mounted` might be returning false because widget might not be fully loaded when coming from `background` to `foreground`. You should rather use https://stackoverflow.com/a/61647060/7363205

**Comment by sacOO7** [comment] 2024-03-04 11:36
Or you can simply update the state after adding some delay. That way, component will be mounted. But it's not that of a efficient way to update component state. you should try above options first.

**Comment by sacOO7** [comment] 2024-03-05 10:34
Hi @walkerJung let me know if above solution worked for you. If it did, we can close the issue.

**Comment by walkerJung** [comment] 2024-03-06 02:43
```
ablyRealtime.connection.on().listen(
      (event) {
        if (mounted) {
          setState(() {
            isAblyConnected = event.current == ably.ConnectionState.connected;
          });
        }
      },
    );
```

I changed my source code like this. It works as expected, but sometimes it takes about 20 seconds for the connection state to change to connected, and I think showing the loader UI during this time is bad for the user experience. Is there a way to connect faster? This is an issue that only happens on Android physical devices

**Comment by walkerJung** [comment] 2024-03-06 03:26
How does the status change of connection work when the app comes back to foreground from background?

**Comment by walkerJung** [comment] 2024-03-06 03:29
I've tested it and the connection state is disconnected when the app goes to the background on an Android real device and comes back to the foreground in 2 to 3 minutes.

**Comment by sacOO7** [comment] 2024-03-06 03:37
Connection has different states =>
CONNECTED => DISCONNECTED => keeps trying to connect with disconnectedRetryTimeout(15s) for 2 minutes => if still not connected goes into SUSPENDED state and keeps retrying indefinitely with suspendedRetryTimeout(30s).

**Comment by sacOO7** [comment] 2024-03-06 03:40
It only goes into FAILED state if error received on connection ( invalid auth token ) is not reytrayable.

**Comment by walkerJung** [comment] 2024-03-06 03:41
When the app moves to the background
The state changes from connected to disconnected,
So you keep trying to reconnect every 15 seconds for 2 minutes even in the background?
If it doesn't reconnect for two minutes, it goes into suspended state
Does it make sense that when you get suspended, you try to reconnect once every 30 seconds?

**Comment by sacOO7** [comment] 2024-03-06 03:43
Yeah, because the error received is `retryable`, I think you should log this behaviour in the logcat or something

**Comment by walkerJung** [comment] 2024-03-06 07:28
It changes back to connected when it's disconnected or suspended, but Android devices seem to take some time, is there any way to speed up this part?

**Comment by sacOO7** [comment] 2024-03-06 07:31
You can set disconnectedRetryTimeout and suspendedRetryTimeout to change the reconnect timeouts.

**Comment by walkerJung** [comment] 2024-03-06 07:32
Even if you set it to 1000ms, there is no difference in the time it connects again

**Comment by sacOO7** [comment] 2024-03-06 07:38
May I ask you to upload the example repo. for this? Also, proper steps to reproduce the same .

**Comment by walkerJung** [comment] 2024-03-06 07:39
It's a little hard to share the entire repository of the app. Is it okay if I share the apk file?

**Comment by sacOO7** [comment] 2024-03-06 07:41
You can create a new project. with `ably` specific flutter code only with keys removed. That shouldn't take much time WDYT. I can test with `apk` file but I will need exact source code to look for proper error.

**Comment by walkerJung** [comment] 2024-03-06 09:05
OK, I'll give it a try.
Is there anything wrong with setting disconnected RetryTimeout and suspendRetryTimeout to 1 second?

**Comment by sacOO7** [comment] 2024-03-06 12:36
No, there's no issue doing that 👍

**Closed** 2024-03-07 00:28 UTC
